/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class UnsafeMemory */

#ifndef _Included_UnsafeMemory
#define _Included_UnsafeMemory
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     UnsafeMemory
 * Method:    allocate
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_UnsafeMemory_allocate
  (JNIEnv *, jclass, jlong);

/*
 * Class:     UnsafeMemory
 * Method:    set
 * Signature: (JLjava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_UnsafeMemory_set
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     UnsafeMemory
 * Method:    get
 * Signature: (J)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_UnsafeMemory_get
  (JNIEnv *, jobject, jlong);

/*
 * Class:     UnsafeMemory
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_UnsafeMemory_free
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
